project:
  type: book
  output-dir: docs

python:
  executable: C:/Users/m_tai/anaconda3/python.exe

book:
  title: "Introduction to R and Python"
  author: "Magno Severino"
  date: "02/04/2025"
  chapters:
    - index.qmd
    - part: Learning R
      chapters: 
        - 01-fundamentos_r.qmd
        - 02-fluxos.qmd
        - 03-dados.qmd
        - 04-visualizacao.qmd
    - part: Learning Python
      chapters:
        - 05-fundamentos_python.qmd
        - 06-visualizacao_python.qmd
    - part: Case studies
      # chapters:
      #   - 07-casos.qmd
    - part: Final Exam
      chapters:
        - 08-prova.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    output-dir: docs/pdf

editor: visual

lang: en    